import re, glob

examples = {
    # Unit 1
    "You will regret it": "If you don't study now, you will regret it later.",
    "A dream comes true": "Getting this job is a dream comes true for me.",
    "Dreaming of": "I am always dreaming of travelling around the world.",
    "Take responsibility for something": "You need to take responsibility for your actions.",
    "Accept responsibility for something": "He refused to accept responsibility for the mistake.",
    "Admit a mistake": "It is hard to admit a mistake, but it's the right thing to do.",
    "Make up an excuse": "Don't make up an excuse for being late.",
    "Tell a lie": "I promise I will never tell a lie again.",
    "Shift the blame": "He tried to shift the blame to his coworker.",
    "Make up for something": "I want to make up for my mistake by helping you.",
    "Do someone a favor": "Could you do me a favor and open the door?",
    "Helping S.O out": "Thank you for helping me out with my homework.",
    "Bite off more than you can chew": "Don't bite off more than you can chew by taking too many classes.",
    "Keep it to yourself": "Please keep this secret to yourself.",
    "Passed with flying colors": "She studied hard and passed the test with flying colors.",
    "Fulfilling": "Teaching is a very fulfilling job.",
    "Achievable": "Set small, achievable goals for yourself.",
    "Requirement": "A university degree is a requirement for this job.",
    "Priority": "My family is always my first priority.",
    "Ambitious": "He is very ambitious and wants to be a manager soon.",
    "Apply for": "I am going to apply for a scholarship.",
    "Apply to": "She wants to apply to a famous university.",
    "Set a goal": "You should set a goal to save money this year.",
    "Determine": "They must determine the cause of the problem.",
    "Get into": "It is difficult to get into that medical school.",
    "Put off": "Don't put off your homework until tomorrow.",
    "Financially independent": "He moved out because he wanted to be financially independent.",
    "Pursue": "Follow your passion and pursue your dreams.",
    "Reject": "The company decided to reject his application.",
    "Get married": "They plan to get married next spring.",
    "Raise": "It costs a lot of money to raise a child.",
    "Change your mind": "You can always change your mind if you don't like it.",
    "Spouse": "Your spouse is your husband or wife.",
    "Fascinating": "The history of Egypt is really fascinating.",
    "To be honest": "To be honest, I didn't like the movie very much.",
    "Flexible": "My schedule is flexible, so I can meet you anytime.",
    "Sensible": "It is sensible to bring an umbrella if it looks like rain.",
    "Suffer": "Many people suffer from the cold weather in winter.",
    "Disappointed": "I was disappointed when we lost the game.",
    "Postpone": "They had to postpone the meeting until next week.",
    "Avoid": "You should try to avoid driving during rush hour.",
    "Down the road": "Who knows what will happen down the road?",
    "Keep one's fingers crossed": "I have an interview today, so keep your fingers crossed for me!",
    "It isn't the end of the world": "You failed one test, but it isn't the end of the world.",
    "Have one's heart set on": "She has her heart set on going to Paris.",
    "Be a matter of time": "It is just a matter of time before he finds the truth.",
    "Be out of one's mind": "You must be out of your mind to swim in freezing water!",
    "Come out": "When will his new book come out?",
    "Bother": "Please don't bother her while she is working.",
    "Disturb": "I'm sorry to disturb you, but I need your help.",
    "Turn out": "The party turned out to be a lot of fun.",
    "Pay off": "All his hard work will finally pay off.",
    "Look forward to": "I look forward to seeing you next week.",
    "Innocent": "The judge declared that he was innocent.",
    "Ignorant": "Many people were ignorant of the new rules.",
    "Billionaire": "He became a billionaire after selling his company.",
    "Philanthropist": "The generous philanthropist donated millions to charity.",
    "Donate": "Would you like to donate old clothes to the poor?",
    "Charity": "She volunteers at a local charity every weekend.",
    "Enormously": "The internet has changed our lives enormously.",
    "Poverty": "Many charities work to reduce poverty in the world.",
    "Tragedy": "The earthquake was a terrible tragedy.",
    "Humanity": "We should treat everyone with humanity and respect.",
    "Volunteering": "Volunteering is a great way to help the community.",
    "Overcome": "With practice, you can overcome your fear of public speaking.",
    "Involve": "The new project will involve a lot of research.",
    "Impact": "Pollution has a negative impact on the environment.",
    "Selfish": "He is selfish and only thinks about himself.",
    "Spoiled": "That spoiled child cries when he doesn't get what he wants.",
    "Brat": "Stop acting like a spoiled brat!",
    "Extravagant": "They had an extravagant wedding with hundreds of guests.",
    "Treating": "She enjoys treating her friends to dinner.",
    "Conscious": "You need to be conscious of your health.",
    "Obscenely": "The house was obscenely large for just two people.",
    "Proportion": "A large proportion of the students live in dorms.",
    "Indicate": "The red light indicates that the machine is on.",
    "Enthusiast": "He is a real sports enthusiast who watches every game.",
    "Billion": "There are over 7 billion people on the planet.",
    "Wealth": "He used his wealth to build a hospital.",
    "Inequality": "Many organizations are fighting against social inequality.",
    "Pledge": "They made a pledge to protect the environment.",
    "Foundation": "The foundation provides money for cancer research.",
    "Vast": "Russia is a vast country with many different climates.",
    "Convince": "I tried to convince my father to buy me a car.",
    "Peers": "Teenagers are often influenced by their peers.",
    "Appeal": "The new phone will appeal to younger buyers.",
    "Regardless": "We will go for a walk regardless of the weather.",
    "Devote": "She wanted to devote her life to helping animals.",
    "Contribute": "Everyone should contribute ideas to the project.",
    "Passion": "Music is his greatest passion.",
    "Expect": "I didn't expect to see you here today!",
    "Colleagues": "My colleagues at the office are very friendly.",
    "Possess": "He possesses a rare talent for painting.",
    "Associate": "I associate the smell of cookies with my grandmother.",
    "Assistant": "The manager asked his assistant to print the report.",
    "Salesclerk": "The salesclerk helped me find the right size.",
    "Project": "Our science project is due next Monday.",

    # Unit 2
    "Preposition": "You use a preposition to show where something is.",
    "Situation": "He remained calm in a stressful situation.",
    "Suppose": "I suppose we could go to the park instead.",
    "Cracking up": "The movie was so funny, it had me cracking up.",
    "Making fun of something": "Stop making fun of my new haircut!",
    "Couldn't help myself": "I laughed because I couldn't help myself.",
    "That’s not the worst of it": "He lost his keys, but that’s not the worst of it.",
    "Cut it out": "You're being too noisy, cut it out!",
    "Own up to something": "You need to own up to your mistakes.",
    "Make it up to someone": "I forgot her birthday, so I must make it up to her.",
    "Psychological": "She is dealing with psychological stress right now.",
    "Participant": "Every participant received a small gift at the end.",
    "Diary": "She writes in her secret diary every night.",
    "Process": "Learning a new language is a slow process.",
    "Punish": "The teacher will punish students who cheat.",
    "Reward": "The club will reward the best player with a trophy.",
    "Stuck in trafic": "Sorry I am late, I was stuck in traffic.",
    "Politician": "The politician promised to create more jobs.",
    "Distinguish": "It is hard to distinguish the twins from each other.",
    "Influence": "Parents have a strong influence on their children.",
    "Sources": "We need to find reliable sources for our research.",
    "Morally": "It is morally wrong to steal from others.",
    "Handle": "He knows how to handle difficult customers.",
    "Peers": "He likes to dress the same way as his peers.",
    "Acquaintance": "He is not a close friend, just an acquaintance.",
    "Categorize": "We categorize the books by subject.",
    "Upbringing": "She had a strict upbringing when she was young.",
    "Dominant": "The home team played a dominant role in the game.",
    "Bully": "You shouldn't let the school bully scare you.",
    "Establish": "They plan to establish a new business next year.",
    "Mission": "Their mission is to provide clean water to villages.",
    "Significant": "There was a significant change in the weather.",
    "Sense": "Dogs have a very good sense of smell.",
    "Divorce": "Her parents' divorce was hard for her.",
    "Shape": "Education helps to shape a country's future.",
    "Selflessness": "His selflessness made him a hero to everyone.",
    "Miracle": "It is a miracle that he survived the crash.",
    "Fragility": "The fragility of the glass means you must handle it with care.",
    "Dilemma": "I am in a dilemma and don't know what to choose.",
    "Activist": "The environmental activist organized a huge protest.",
    "Refugee": "The refugee crossed the border to escape the war.",
    "Wealthy": "They live in a large house in a wealthy neighborhood.",
    "Numerous": "He has won numerous awards for his music.",
    "Decade": "The internet has changed a lot in the last decade.",
    "Oppose": "I strongly oppose the new rules.",
    "Nuclear": "Many countries want to reduce nuclear energy.",
    "Weapons": "The police found illegal weapons in his car.",

    # Unit 3
    "Scary": "That horror movie was really scary.",
    "Passenger": "The driver asked the passenger to put on a seatbelt.",
    "Taking a roller-coaster ride": "Taking a roller-coaster ride is thrilling but scary.",
    "Edge": "Don't put your glass so close to the edge of the table.",
    "Turbulence": "The flight was bouncy because of turbulence.",
    "Undergo": "She has to undergo surgery on her knee.",
    "In hot water": "If you don't finish the report, you'll be in hot water.",
    "Get cold feet": "He was going to jump, but he got cold feet.",
    "Commitment": "Marriage is a lifelong commitment.",
    "Pulled the rug out from under her": "Losing her job suddenly pulled the rug out from under her.",
    "With all my heart": "I love my family with all my heart.",
    "I just can’t take the plunge": "I want to start a business, but I just can't take the plunge.",
    "Jump to that conclusion": "Let's wait for the facts before we jump to that conclusion.",
    "A big deal": "Don't worry, a small mistake is not a big deal.",
    "It’s not the end of the world": "You failed the driving test, but it's not the end of the world.",
    "Freaks you out": "Seeing a spider always freaks you out.",
    "Mark my words": "Mark my words, he will become a great leader one day.",
    "Just chill": "You're too stressed, you need to just chill out.",
    "Frustration": "He shouted in frustration when his computer crashed.",
    "Fed up": "I am fed up with the terrible traffic in this city.",
    "Empathy": "She showed great empathy by listening to his problems.",
    "Discouraging": "It is discouraging to work hard and fail.",
    "Encouragement": "Children need encouragement from their teachers.",
    "Embarrassing": "It was embarrassing when I forgot his name.",
    "Fiancee's parent": "He is going to meet his fiancee's parent tonight.",
    "Panic": "There is no need to panic; please stay calm.",
    "Butterflies in my stomach": "I had butterflies in my stomach before the big speech.",
    "Palpitations": "Too much coffee gives me heart palpitations.",
    "Pretend": "Let's pretend we are pirates looking for gold.",
    "Stuck": "The wheels of the car got stuck in the mud.",
    "Deaf": "He speaks sign language because he is deaf.",
    "Stage": "The actors walked out onto the stage.",
    "Spokesperson": "The company spokesperson answered questions from the news.",
    "Disability": "The building has a ramp for people with a physical disability.",
    "Devoted": "She is a devoted mother who loves her kids.",
    "Expectation": "My parents have high expectations for my grades.",
    "Permanent": "The tattoo is permanent, so choose carefully.",
    "Suffered": "The city suffered heavy damage from the storm.",
    "Fever": "He stayed in bed because he had a high fever.",
    "Approached": "A stranger approached me and asked for directions.",
    "Boarding school": "He lived away from his family at a boarding school.",
    "Essential": "Water and food are essential for survival.",
    "Deprived": "The kidnapped child was deprived of food and sunlight.",
    "Mainstream": "He prefers independent movies to mainstream ones.",
    "Ashamed": "Don't be ashamed to ask for help.",
    "Strange": "I heard a strange noise outside the window.",
    "Joy": "Her face was filled with joy when she won.",
    "Disorder": "He suffers from a rare blood disorder.",
    "Dyslexia": "Dyslexia makes it difficult for him to read quickly.",
    "Pursue": "It takes courage to pursue your dreams.",
    "Controversy": "The new law caused a lot of controversy.",
    "Nominee": "She is an Oscar nominee for Best Actress.",
    "Surpass": "The company hopes to surpass its sales goals this year.",
    "Incredulous": "He gave an incredulous look when he heard the crazy story.",
    "Function": "What is the function of this button?",
    "Brave": "It was very brave of you to stand up to the bully.",
    "Courageous": "The courageous firefighter saved the family.",
    "Fearless": "The fearless soldier led his team forward.",
    "Willing": "I am willing to help you if you need me.",

    # Unit 4
    "Disorganized": "His desk is so disorganized that he can't find anything.",
    "Set off = Go": "We need to set off early to catch the train.",
    "Oversensitive": "Don't be oversensitive; it was just a joke.",
    "Overreact": "Try not to overreact when bad things happen.",
    "Perfectionist": "As a perfectionist, she spends hours fixing every little detail.",
    "Atýtude": "You need a positive attitude to succeed. (Attitude)",
    "Lost one’s cool": "The boss lost his cool and yelled at everyone.",
    "Set S.O off": "Mentioning politics is enough to set him off.",
    "Makes a big issue out of": "She makes a big issue out of every little mistake.",
    "Tell S.O off": "The teacher had to tell the student off for talking.",
    "Bring it up": "I didn't want to bring it up because it's a sensitive topic.",
    "Take it well": "He didn't take the bad news well at all.",
    "Walk on eggshells": "When my dad is angry, we all have to walk on eggshells.",
    "Pick up the pieces": "After the fire, the family tried to pick up the pieces.",
    "Pile up": "My emails pile up quickly if I don't check them daily.",
    "Interfering": "I wish she would stop interfering in my personal life.",
    "Workshop": "I attended a photography workshop last weekend.",
    "Journey": "The train journey takes about three hours.",
    "Strategy": "We need a new strategy to win the game.",
    "Even if": "Even if it rains, we are going hiking.",
    "Whether or not": "We are leaving tomorrow whether or not you are ready.",
    "Unless": "I won't go unless you come with me.",
    "Otherwise": "Hurry up, otherwise you will miss the bus.",
    "No matter": "I will love you no matter what.",
    "Lost one’s temper": "He lost his temper and threw the book across the room.",
    "Have a fit = Go ballistic": "My mom will go ballistic if I break her favorite vase.",
    "Hit the roof": "When he saw the damage to his car, he hit the roof.",
    "Blow one’s top": "Don't blow your top just because of a small mistake.",
    "Hold it in = Keep it inside": "If you are sad, don't hold it in; talk to someone.",
    "Let it go = Shrug it off": "Just let it go and don't worry about it.",
    "Let off steam": "He goes for a run after work to let off steam.",
    "Vent": "She called her best friend to vent her frustration.",
    "Jealous": "She was jealous of her sister's new toy.",
    "On the contrary": "I'm not sick; on the contrary, I feel great.",
    "Cheer": "The crowd began to cheer when the team scored.",
    "Bridge": "We drove over the bridge to cross the river.",
    "Count": "Can you count to ten in Spanish?",
    "Upset": "Don't be upset about missing the party.",
    "Accommodate": "The hotel can accommodate up to 500 guests.",
    "Judge": "You shouldn't judge a book by its cover.",
    "Flaw": "The only flaw in your plan is the high cost.",
    "Stick up": "A good friend will always stick up for you.",
    "Stick": "Use glue to stick the paper to the wall.",
    "Crucial": "Sleep is crucial for good health.",
    "Mutual": "The friendship is based on mutual respect.",

    # Unit 5
    "Mortify": "It would mortify her if anyone saw her baby pictures.",
    "Ketchup": "Do you want some ketchup with your fries?",
    "It went over like a lead balloon": "His joke went over like a lead balloon; no one laughed.",
    "I made a total fool of myself": "I made a total fool of myself by tripping on stage.",
    "It just isn’t done": "You shouldn't wear that to a wedding; it just isn't done.",
    "I don’t get it": "I don't get the punchline of that joke.",
    "Par for the course": "Working late is par for the course in this company.",
    "Don’t take it so hard": "You didn't pass, but don't take it so hard. You can try again.",
    "Easier said than done": "Saving money is easier said than done.",
    "Sophisticated": "She has a very sophisticated taste in art.",
    "Slapstick": "Children usually enjoy slapstick comedy with funny physical actions.",
    "Warmth": "We could feel the warmth of the sun on our skin.",
    "Internal organ": "The heart is an important internal organ.",
    "Suffering": "The medicine will ease the patient's suffering.",
    "Prove": "He needs to find evidence to prove his theory.",
    "Laid the foundation": "The discovery laid the foundation for modern medicine.",
    "Life-threatening": "The car crash caused life-threatening injuries.",
    "Chronic": "He suffers from chronic back pain.",
    "Healing": "The cut on his arm is slowly healing.",
    "Cure": "Scientists are trying to find a cure for cancer.",
    "Contagious": "Keep him at home because the flu is contagious.",
    "Hysterical": "The movie was so funny, we were hysterical.",
    "Priceless": "The painting in the museum is considered priceless.",
    "Misfortune": "He had the misfortune of losing his wallet on holiday.",
    "Mispronounce": "Foreigners often mispronounce my difficult name.",
    "Ridiculous": "It is ridiculous to wear shorts in snowy weather.",
    "Psychiatrist": "She visited a psychiatrist to talk about her depression.",
    "Dirty joke": "He told a dirty joke that made everyone uncomfortable.",
    "Ethnic joke": "An ethnic joke can be very offensive.",
    "Sexist joke": "Making a sexist joke is not appropriate in the workplace.",
    "Political joke": "The comedian told a political joke about the president.",
    "Verbal joke": "A verbal joke relies on clever wordplay.",
    "Be the butt of a joke": "He did not like being the butt of the joke.",
    "Be in bad ( or poor) taste": "Laughing at a funeral is in very bad taste.",
    "Cross the line": "Your joke crossed the line and hurt her feelings.",
    "Drawer": "I keep my socks in the top drawer.",
    "Swallow": "Chew your food well before you swallow.",
    "Insulting": "His comments about my weight were very insulting.",

    # Unit 6
    "Hassle": "Finding parking in the city is such a hassle.",
    "Contest": "She won first prize in the singing contest.",
    "Direction": "Could you give me directions to the hospital?",
    "Inedible": "The meat was burnt and completely inedible.",
    "Baggage = Luggage": "We need to collect our baggage from the carousel.",
    "Insufícient room in overhead bins": "There is insufficient room in overhead bins for all bags.",
    "Insufícient": "Her explanation was insufficient to clear her name.",
    "Security screening": "Please take off your shoes for the security screening.",
    "Confiscate": "The guard will confiscate your water bottles.",
    "Mechanical breakdown": "The flight was delayed due to a mechanical breakdown.",
    "Flat tire": "We had a flat tire and had to fix it by the road.",
    "Getýng towed for parking illegally": "He worried about getting towed for parking illegally.",
    "Get lost": "If you don't use a map, you might get lost.",
    "Trafíc jams": "I hate driving to work during traffic jams.",
    "Passport": "You must show your passport at the border.",
    "Boarding pass": "Print your boarding pass before you go to the gate.",
    "The front desk": "Leave your keys at the front desk of the hotel.",
    "Downstairs": "The dining room is located downstairs.",
    "Distinctly": "I distinctly remember telling you to lock the door.",
    "Slammed": "He slammed the door shut when he was angry.",
    "Rushing": "There is no need for rushing; we have plenty of time.",
    "I’m drawing a blank": "I try to remember his name, but I'm drawing a blank.",
    "It’s a safe bet": "It's a safe bet that it will rain tomorrow.",
    "The way i see it": "The way I see it, we have no other choice.",
    "I’m toast": "If my mom finds out I broke the TV, I'm toast.",
    "You will cross that bridge when you come to it": "Don't worry about the final exam yet; cross that bridge when you come to it.",
    "I’m off": "Well, it's late. I'm off to bed.",
    "Perfume": "She's wearing a very strong perfume.",
    "Depart": "The train will depart from platform 3.",
    "Lull": "There was a short lull in the storm before it started raining again.",
    "Downside": "The only downside to this phone is its poor battery life.",
    "Access": "You need a password to access this computer.",
    "Pattern": "This dress has a beautiful floral pattern.",
    "Fraud alert": "I received a fraud alert on my credit card app.",
    "Impersonate": "It is illegal to impersonate a police officer.",
    "Scenario": "Let's imagine a scenario where we win the lottery.",
    "Encryption": "The website uses encryption to protect your data.",
    "Unintelligible": "The writing on the old letter was completely unintelligible.",
    "Wireless": "We use a wireless network at home.",
    "Hotspot": "You can connect to the Wi-Fi hotspot in the cafe.",
    "Credential": "Please enter your login credential to proceed.",

    # Unit 7
    "Illusion": "The magician created an amazing optical illusion.",
    "Explanation": "Can you give me an explanation for being late?",
    "What's on your mind": "You look sad. What's on your mind?",
    "I may be imagining things = It’s possible that what I’m thinking is an illusion": "I may be imagining things, but I think someone is following us.",
    "Keep in mind": "Keep in mind that the store closes early on Sunday.",
    "Don’t get me wrong": "Don't get me wrong, I like the color, but the size is too big.",
    "The cat’s out of the bag": "Now that you know the secret, the cat's out of the bag.",
    "Distinct": "The two birds belong to distinct species.",
    "Impression": "He made a good first impression at the interview.",
    "Automatic": "The hotel has automatic doors that open when you get close.",
    "Innocent": "I really believe he is an innocent man.",
    "Gossiping": "They spend too much time gossiping about their coworkers.",
    "Superstitious": "Some superstitious people believe black cats bring bad luck.",
    "Select": "Please select the song you want to play.",
    "Wide": "The river is too wide for us to swim across.",
    "Wealth": "She inherited great wealth from her grandparents.",
    "Associated": "Dark clouds are usually associated with a storm.",
    "Doomed": "Without funding, the project is doomed to fail.",
    "Predict": "It is hard to predict the weather accurately.",
    "Swing": "The kids love playing on the swing in the park.",
    "Sink": "The ship began to sink after it hit the rocks.",
    "Rat": "I saw a huge rat run under the house.",
    "Signify": "A red traffic sign signifies that you must stop.",
    "Placebo": "Half the patients were given real medicine, and half got a placebo.",
    "Refer": "This textbook refers to earlier scientific studies.",
    "Active ingredient": "The active ingredient in this pill stops headaches.",
    "Procedure": "What is the normal procedure for opening a new account?",
    "Well-known": "He is a well-known actor in his country.",
    "Knee": "I hurt my knee while playing football.",
    "Interior": "The interior of the house was painted white.",
    "Repeatedly": "I tried calling him repeatedly, but he didn't answer.",
    "Pill": "You need to swallow this pill with a glass of water.",
    "Genuine = Real": "This bag is made of genuine leather.",
    "Disadvantage = Adverse": "One adverse effect of the drug is sleepiness.",
    "Actual": "The actual cost was much higher than we thought.",

    # Unit 8
    "be good with one's hands": "He fixes cars because he is good with his hands.",
    "be mechanically inclined": "She can repair any machine because she is mechanically inclined.",
    "challenge yourself": "You should try a new hobby to challenge yourself.",
    "curious / inquisitive": "The curious child asked a lot of questions.",
    "develop a routine": "It helps to develop a routine for doing homework.",
    "go offline": "Sometimes I just want to go offline and read a book.",
    "goes in one ear and out the other": "Every time I scold him, it just goes in one ear and out the other.",
    "gut feeling": "I had a gut feeling that something was wrong.",
    "have a good intuitive sense": "She has a good intuitive sense about people's feelings.",
    "have a head for figures": "He should be an accountant because he has a head for figures.",
    "have a knack for learning languages": "Some people just have a knack for learning languages quickly.",
    "have a way with people": "She naturally has a way with people and makes them feel comfortable.",
    "have a way with words": "The poet has a beautiful way with words.",
    "have an ear for music": "He has an ear for music and can easily play any tune.",
    "have an eye for detail": "An editor needs to have an eye for detail to catch spelling mistakes.",
    "I can't help it": "I know chocolate is bad for me, but I can't help it.",
    "inventive / imaginative": "An inventive engineer designed this brand-new engine.",
    "it's now or never": "If you want to travel, it's now or never.",
    "make a list": "When you go grocery shopping, please make a list.",
    "open-minded": "You should be open-minded when trying foods from different cultures.",
    "out of the blue": "The storm came completely out of the blue.",
    "perceptive / observant": "He is a perceptive teacher who knows when students are struggling.",
    "persistent": "He was very persistent, so he finally got the job.",
    "put your nose to the grindstone": "Exams are next week, so it's time to put your nose to the grindstone.",
    "reserve 'do not disturb' time": "I reserve 'do not disturb' time in the morning to focus.",
    "stay organized": "Use a calendar app to stay organized.",
    "take a breather": "You've been studying for hours; take a breather.",
    "talented": "She is a talented singer who performs all over the world.",
    "witty": "His speech was smart and very witty.",

    # Unit 9
    "Surgeries": "He stayed in the hospital after three surgeries.",
    "Petroleum": "Gasoline is made from petroleum.",
    "Delivered": "The package was delivered to my house this morning.",
    "Prediction": "The weather prediction says it will snow tomorrow.",
    "Scale": "We need to weigh this on a kitchen scale.",
    "Probability": "There is a high probability that it will rain tonight.",
    "Cancer": "Smoking increases the risk of getting lung cancer.",
    "Obsolete": "Typewriters are now obsolete because we use computers.",
    "Vehicle": "A bicycle is a vehicle that does not use gas.",
    "Digital technology": "Cameras changed forever with the invention of digital technology.",
    "Agriculture": "Agriculture is the main industry in this farming region.",
    "Sighting": "There was a rare sighting of a bear near the river.",
    "Takeoff": "Please fasten your seatbelts for takeoff.",
    "Landing": "The plane had a smooth landing at the airport.",
    "It’ll open a can of worms": "Asking him about his ex-wife will just open a can of worms.",
    "Before you know it": "Practice every day, and before you know it, you'll be fluent.",
    "Come to think of it": "Come to think of it, I did see him yesterday.",
    "It isn’t a question of if but when": "Technology will replace these jobs; it isn't a question of if but when.",
    "It’s just scratching the surface": "We learned a little, but it's just scratching the surface.",
    "The bad outweighs the good": "I dislike the job because the bad outweighs the good.",
    "Drone": "He used a drone to take video from the sky.",
    "Institution": "The university is an educational institution.",
    "Envisioning": "I am envisioning a future where all cars are electric.",
    "Maglev": "A maglev train floats above the tracks using magnetic forces.",
    "Magnet": "The magnet stuck firmly to the refrigerator.",
    "Route": "We took the scenic route through the mountains.",
    "Alternative": "Oat milk is a popular alternative to cow's milk.",
    "Identification": "Please show your identification at the front desk.",
    "Construct": "They plan to construct a new bridge across the river.",
    "Spectacular": "The fireworks display over the bay was spectacular.",
    
    # Unit 10
    "Approximately": "The journey will take approximately two hours.",
    "Pros": "What are the pros and cons of moving to a new city?",
    "Cons": "One of the cons of living here is the heavy traffic.",
    "On the fence = Not able to decide something": "I am still on the fence about which car to buy.",
    "It\\'s bad enough that": "It's bad enough that we lost, but you don't need to yell at us.",
    "It's bad enough that": "It's bad enough that we lost, but you don't need to yell at us.",
    "A fish out of water = Everything seems unfamiliar to you": "As a country boy in the big city, he felt like a fish out of water.",
    "Pulls your leg = He or she is only kidding": "Don't believe him; he always pulls your leg.",
    "A losing battle = It\\'s probably best to give up": "Trying to keep the house clean with four dogs is a losing battle.",
    "A losing battle = It's probably best to give up": "Trying to keep the house clean with four dogs is a losing battle.",
    "Money talks": "In politics, it's often true that money talks.",
    "Proficient": "She is proficient in three languages.",
    "Bring about": "The new manager hopes to bring about positive changes.",
    "Carry out": "The doctors will carry out some tests to find the problem.",
    "Come down with": "I think I might come down with a cold.",
    "Come up with": "He tried to come up with a good excuse for being late.",
    "Go without": "We had to go without water for two days.",
    "Lay off": "The company had to lay off 100 workers.",
    "Put up with": "I can't put up with this noise anymore.",
    "Run out of": "We need to buy milk because we ran out of it.",
    "Wipe out": "The disease could wipe out the entire animal population.",
    "Refugees": "The camp provided shelter for thousands of refugees.",
    "Terrorist organizations": "The government is trying to stop terrorist organizations.",
    "Humanitarian": "The charity provides humanitarian aid to earthquake victims.",
    "Agencies": "Several relief agencies are working together here.",
    "Troops": "The general ordered the troops to march forward.",
    "Settle into": "It took him a few weeks to settle into his new job.",
    "Vulnerable": "Newborn animals are weak and vulnerable.",
    "Malnourished": "The malnourished children urgently need healthy food.",
    "But on the bright side": "My car broke down, but on the bright side, I got some exercise walking.",
    "It just goes to show you": "It just goes to show you that hard work really pays off.",
    "Run into": "I didn't expect to run into an old friend at the supermarket.",
    "Came across": "I came across my old photos while cleaning the room.",
    "Care for": "Would you care for a cup of tea?",
    "Talk into": "He managed to talk me into buying the expensive watch.",
    "Throw away": "Don't throw away those old clothes; donate them.",
    "Try on": "You should try on the shoes before you buy them.",
    "Try out": "Let's try out this new restaurant tonight.",
    "Count on": "You can always count on me when you need help.",
    "Figure out": "I need to figure out how to solve this math problem.",
    "Gadget": "He loves buying every new electronic gadget.",
    "Visible": "The mountains are visible in the distance on a clear day.",
    "Tech-savvy": "My grandfather is surprisingly tech-savvy with his smartphone.",
    "Tremendous": "The explosion made a tremendous noise.",
    "Separable": "The prefix 'un-' is separable from the root word.",
    "Interconnected": "The global economy is deeply interconnected.",
    "Advocates": "He strongly advocates for better public transportation.",
    "Instant messaging": "We use instant messaging to communicate quickly at work.",
    "Teleconference": "The team had a teleconference with the London office.",
    "Prosperity": "We wish you health and prosperity in the new year.",
    "Critics": "The movie critics gave the film terrible reviews.",
    "Evidence": "The police found no evidence at the crime scene.",
    "Manufacturing": "This country's economy relies heavily on manufacturing.",
    "Flourished": "The business flourished after moving to the city center.",
    "Homogenization": "The homogenization of culture means many cities look the same now.",
    "Investment": "Buying a house is a solid long-term investment.",
    "Cartel": "An illegal cartel controls the prices of that product.",
    "Disorienting": "Being in a foreign country without knowing the language can be disorienting.",
    "A light at the end of the tunnel": "After months of hard study, exam day is finally the light at the end of the tunnel."
}

import traceback
def inject_examples():
    for file in glob.glob('unit*.html'):
        try:
            with open(file, 'r', encoding='utf-8') as f:
                content = f.read()

            def replacer(match):
                full_obj = match.group(0)
                word = match.group(1)
                example = examples.get(word, examples.get(word.replace("\\'", "'"), ""))
                if example:
                    # Replace phrase: "" or phrase: "..." with phrase: "example"
                    return re.sub(r'phrase:\s*\"[^\"]*\"', f'phrase: "{example}"', full_obj)
                return full_obj

            new_content = re.sub(r'\{[^}]*word:\s*\"([^\"]+)\"[^}]*phrase:\s*\"([^\"]*)\"[^}]*\}', replacer, content)

            with open(file, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"Processed {file}")
        except Exception as e:
            print(f"Error processing {file}: {e}")
            traceback.print_exc()

if __name__ == '__main__':
    inject_examples()
